version: "3"

vars:
  # Define the version in one central place.
  VERSION: 0.1.1
  # Construct the ldflags string. Note the full path to the 'version' variable.
  LDFLAGS: '-ldflags="-X ''code2md/cmd/cli.version={{.VERSION}}''"'

env:
  PGM_NAME: code2md

tasks:
  build:
    deps: [typo, format, lint]
    cmds:
      - go mod tidy
      # Update the build command to include the ldflags.
      - go build {{.LDFLAGS}} -o $PGM_NAME .
  format:
    cmds:
      - go fmt ./...
  install:
    deps: [build]
    cmds:
      - cp $PGM_NAME ~/bin/
  lint:
    deps: ["lint:wsl"]
    cmds:
      - golangci-lint run ./... -v
  lint:wsl:
    cmds:
      - golangci-lint run ./... --no-config --enable wsl_v5 --fix
  test:
    cmds:
      - go test ./...
  typo:
    cmds:
      - typos *.go
  typo:fix:
    cmds:
      - typos -w *.go
