name: Build and Test
on:
  push:
    tags:
      - "v*.*.*" # This workflow runs on tags like v1.0.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Task
        uses: arduino/setup-task@v2

      # Install the golangci-lint binary
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1

      # Install the typos-cli binary, which is a dependency for the 'build' task
      - name: Install typos-cli
        run: |
          # 1. Create a standard directory for binaries and add it to the PATH
          mkdir -p $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH
          # 2. Define the version and asset URL
          TYPOS_VERSION=v1.32.0
          URL="https://github.com/crate-ci/typos/releases/download/${TYPOS_VERSION}/typos-${TYPOS_VERSION}-x86_64-unknown-linux-musl.tar.gz"
          # 3. Download and extract the entire archive into the current directory
          curl -sL "$URL" | tar -xz
          # 4. Move the executable directly to the bin directory
          # The typos binary is extracted directly to the current directory
          mv typos $HOME/bin/
          # 5. Verify the installation using the full path (PATH changes take effect in next step)
          $HOME/bin/typos --version

      # Verify PATH is set correctly for subsequent steps
      - name: Verify PATH
        run: |
          echo "PATH: $PATH"
          which typos

      # Now that all dependencies are installed, we can run our tasks.
      - name: Run Linters
        run: task lint

      - name: Run Tests
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      # This command should now succeed because its dependency 'typos' can be executed.
      - name: Build Application
        run: task build

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: code2md-binary-ubuntu
          path: code2md
