name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Task
        uses: arduino/setup-task@v2

      # Replace 'v2.2.1' with the version from your 'golangci-lint --version' command.
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1

      - name: Run Tests with Race Detector and Coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      # Buil the app
      - name: Build Application
        run: go build -o code2md .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: code2md-binary-ubuntu
          path: code2md
